InternalClassType: Method
Coordinate3D: [-5,10,0]
Name: openConfig
Origin: fc2f43cc-3b9c-465a-b606-f67c6c4c3be5
Program: |+1
 -- called by the context menu
 dialog.open
 Dialog.setIndex("Register",2)

RandomSeed: 69
UUID: 87d1f32c-5997-4b0e-a39f-6be50d40936d
$IconAttributes:
 Matrix: [1,0,0,1]
 ChangedRotation: true
 ChangedScaling: true
