InternalClassType: DataTable
Coordinate3D: [49.5,-18.85,0]
Name: DS_ObservValues
Origin: d6182412-ec21-4632-8495-4f754642cb1e
UUID: e967ea3b-344d-4a84-874b-fb32a47f07fd
$CustomAttributes:
-
 Name: deleteTmpTables
 DataType: method
 RandomSeed: 169
 Value: |+1
  -- called by:_prepareReport,_resetWizard
  var t:table := self.~.tmpTables
  for var j := 1 to t.yDim 
  	if t[1,j] /= void 
  		t[1,j].deleteObject
  	end
  next
  t.delete
-
 Name: tmpTables
 DataType: table
 Value:
  Comment: ~
  CommonFormat: false
  ListFormat:
   ColumnWidth: 20
   DataType: string
   ShowDataType: true
   ColumnFormat:
   -
    Index: 1
    DataType: object
  Columns:
-
 Name: OutputValue
 DataType: string
 Value: ""
$Data:
 Comment: ~
 ListFormat:
  ColumnIndex: true
  ColumnWidth: 12
  DataType: string
  ShowDataType: true
  ColumnFormat:
  -
   Index: 1
   DataType: integer
  -
   Index: 2
   DataType: integer
  -
   Index: 3
   DataType: real
  -
   Index: 4
   DataType: real
  RowFormat:
  -
   Index: 0
   DataType: string
 ColumnIndex: [string,5,~,"ExpNo","ObservNo","OutputVal 1","OutputVal 2"]
 Columns:
