InternalClassType: DataTable
Coordinate3D: [13,-6.0499999999999989,0]
Name: OutputValues
Origin: d6182412-ec21-4632-8495-4f754642cb1e
UUID: b5d27e1a-b2e3-4a68-a42b-3580b0bc5f9b
$Data:
 Comment: ~
 ListFormat:
  ColumnIndex: true
  ColumnWidth: 10
  DataType: real
  FormatString: "-15.2"
  RowIndex: true
  ShowDataType: true
  ColumnFormat:
  -
   Index: 0
   Hidden: false
   Width: 11
  -
   Index: 1
   Width: 10
  -
   Index: 2
   Width: 10
  -
   Index: 3
   Width: 10
  -
   Index: 4
   Width: 10
 ColumnIndex: [string,1,"Target value"]
 Columns:
